settings:
    log_mode: text
    log_level: INFO
    output_mode: json
    update_interval: 500
    market_pairs:
        - BTC/USDT
        - ETH/USDT

exchanges:
    binance:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1d
          period_count: 50
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1d
          period_count: 14
    stoch_rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 1d
          period_count: 14
    momentum:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - momentum
          hot: 0
          cold: 0
          candle_period: 1d
          period_count: 10
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - momentum
          hot: 0
          cold: 0
          candle_period: 1d
          period_count: 12
    macd:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - macd
          hot: 0
          cold: 0
          candle_period: 1d
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - macdsignal
          hot: 0
          cold: 0
          candle_period: 1d
    obv:
        - enabled: false
    mfi:
        - enabled: false
          alert_enabled: false
          alert_frequency: once
          signal:
            - mfi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14
    ichimoku:
        - enabled: false

informants:
    ema:
        - enabled: true
          signal:
            - ema
          candle_period: 1d
          period_count: 10
        - enabled: true
          signal:
            - ema
          candle_period: 1d
          period_count: 30

crossovers:
    std_crossover:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: macd
          key_indicator_index: 0
          key_indicator_type: indicators
          key_signal: macd
          crossed_indicator: macd
          crossed_indicator_index: 1
          crossed_indicator_type: indicators
          crossed_signal: macdsignal

notifiers:
    discord:
        required:
            webhook: https://discord.com/api/webhooks/1342436387324170300/l_7TiNJta5oQb_xe_6iFkTZ0s3sPdPP_sAz0eTtcKicfWAsq3H4nbgTu9zHOHfY-Jjo6
            username: Noti Coin
        optional:
            avatar: ''
            template: >-
                {{exchange}} - {{market}} | MACD: {{values}} |
                {% if analysis.result.is_hot %} BUY (Green) {% elif analysis.result.is_cold %} SELL (Red) {% else %} Neutral {% endif %}

